### ISSUE TITLE
Remove Fork-relationship to rancilio-pid/ranciliopid

### ISSUE THREAD

**Issue by nils-werner** [medlor/bleeding-edge-ranciliopid#25]
Hi,

as `ranciliopid` and `bleeding-edge-ranciliopid` are clearly [not able/interested in merging each others changes](https://github.com/rancilio-pid/ranciliopid/network), they don't necessarily need to be *GitHub Forks* of each other.

Right now, they are GitHub Forks, which makes it impossible for me to fork both repos into my own namespace. I have forked bleedingedge before, and have submitted a PR. If I now want to fork ranciliopid to create a PR, GitHub tells me that I already have a fork.

Could you please consider removing the Fork relation so that people can contribute to both projects?

Thanks

**Comment by medlor** [comment]
Hi Nils-Werner,

you can check https://stackoverflow.com/questions/12338240/how-can-i-fork-the-original-repo-when-ive-already-forked-a-different-fork on how to archive this without me removing the link.

**Comment by nils-werner** [comment]
The SO post says that it isn't possible though...

**Comment by medlor** [comment]
I dont understand the real issue. There are multiple ways around the github limitation.

If you really need 2 forks of the same "repo" then you can try https://handong1587.github.io/linux_study/2015/12/18/create-multi-forks.html . But why is that needed, when you can also just e.g. stick to https://stackoverflow.com/a/12348696 .

**Comment by nils-werner** [comment]
I know that it is technically possible, and I know how to deal with multiple remotes and all of that.

The issue is that my local `master` branch won't have a proper relationship to a remote branch. There will be `ranciliopid/master` and `medlor/master`, and I have to be very careful when checking out one or the other.

It is basically the same as cloning two different projects into the same local repository: `numpy/master` and `laravel/master`. Technically, you can do that, and work with it. But it will be a pain to deal with...
