### ISSUE TITLE
"Booting" signal

### ISSUE THREAD

**Issue by nils-werner** [medlor/bleeding-edge-ranciliopid#32]
I've now had it a few times that the arduino didn't boot properly (e.g. when rebooting it too quickly), which I didn't notice and the machine then just stayed cold.

Is it possible to implement a "booting" signal, like blink an LED, or trigger the valve after bootup?

**Comment by P1Rebo** [comment]
Hi @nils-werner, depending on the current state you could add some code lines to set some led outputs.

**Comment by medlor** [comment]
there is functionality for the brewLed which of cause can be used on startup as boot indicator

**Comment by medlor** [comment]
uhm..my rancilio silvia led lights up when the boiler has power. I am using this (and my external display) to see if the maschine runs.

**Comment by medlor** [comment]
2.6.0 beta 5 will have this feature: hardware led glows in setup() phase (for a couple of seconds).
