### ISSUE TITLE
Unneccary libraries included

### ISSUE THREAD

**Issue by lebuni** [medlor/bleeding-edge-ranciliopid#43]
Hey Tobias!
Ich hab gerade mal versucht, deine 2.7.0 auf einem ESP32 zum Laufen zu bringen, um meine [ZACwire-Library beta](/lebuni/ZACwire-Library/tree/beta) zu testen. Meine userConfig hab ich folgendermaßen angepasst:
```c++

#define FORCE_OFFLINE 1       // 0=Use network | 1=Disable all network stuff (WiFi, MQTT, Blynk).
[...]
#define TEMPSENSOR 2          // 1=DS19B20; 2=TSIC306. It is not recommended to use DS19B20 due to latencies.
[...]
#define DEBUG_FORCE_GPIO_CHECK   0  // 0=off (default). 1=on. If on, PID is disabled and only trigger/toogles...
[...]
#define DISPLAY 0                         // 0=Deaktiviert, 1=SH1106_128X64, 2=SSD1306_128X64
```
Leider kompiliert das Programm so nicht. Zuerst wird nach MQTT gefragt (was ich ja eigentlich mit FORCE_OFFLINE deaktiviert hab), dann nach einer Display-library (was mit DISPLAY 0 deaktiviert ist) und schließlich nach libraries für den DS19B20 (den ich mit TEMPSENSOR auch deaktiviert haben sollte).
Weiter hab ich jetzt nicht rumprobiert, aber generell könnte man sich mal anschauen, was vom Code man wirklich braucht. Es macht ja keinen Sinn, sich eine library für ein Display zu installieren, das man gar nicht besitzt.

**Comment by medlor** [comment]
Hi Adrian,
hast absolut Recht. Danke für den Reminder.

Ich muss im Code noch einiges aufräumen und bin mittlerweile mit der Code-Qualität nicht so zufrieden. Das werde ich beizeiten angehen.

**Comment by medlor** [comment]
ich schliess das issue mal.. mach ich demnächst.
