### ISSUE TITLE
Checkout of branch master not possible

### ISSUE THREAD

**Issue by aschoelzhorn** [medlor/bleeding-edge-ranciliopid#48]
When checking out master or 2.9.0_beta (did not check other branches), I get the following error:

> error: invalid path '3d-models/dual-ssr-relay-case/Case upper_v5.stl:com.dropbox.attrs'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

There are two files with which are preventing a checkout. Both have the ``:com.dropbox.attrs`` ending.

I'll prepare a PR to fix this problem.

**Comment by medlor** [comment]
Thank you for your help!
