### ISSUE TITLE
Huge delay on ESP32 boards

### ISSUE THREAD

**Issue by mwelcker** [medlor/bleeding-edge-ranciliopid#60]
The PID loop suffer under huge delays on ESP32 boards. The issue did not occur on the ESP8266 as i know so far.
I suffered from delays up to 900ms.

Here are some logs indicating the problem:
```
(E p:^0013ms) 232 refreshTemp(): Delay=205 ms (loop() hang?)
(D p:^0606ms) 232 temp sensor read failed: consecErrors=1, secondlatestTemperature=93.20, latestTemperature=222.00
```

I want to start some research on that issue. Maybe I am able to taggle it down.

**Comment by medlor** [comment]
Hi,
i only have delays one very rare cases, like when I am connecting to the device using telnet. 
Can you send me a full log (including the initial lines where the config is printed)?

Also can you reproduce this on certain actions or does this lag happen all the time?

**Comment by medlor** [comment]
i assume this is related to https://github.com/medlor/bleeding-edge-ranciliopid/pull/59 ? If yes, then the temperature reading lib just takes that much time. As said (on discord) I propose to not use this sensor because it is just to inaccurate and reading takes way too much time.
